export const SCREEN_SHOWED = 'SCREEN_SHOWED';
export const SALE = 'SALE';
export const SIGN_UP = 'SIGN_UP';
export const CASH_MANAGEMENT = 'CASH_MANAGEMENT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';

export const PROGRESS_VISIBLE_CHANGE = 'PROGRESS_VISIBLE_CHANGE';
export const PROGRESS_MESSAGE_CHANGE = 'PROGRESS_MESSAGE_CHANGE';
export const PROGRESS_SIZE_CHANGE = 'PROGRESS_SIZE_CHANGE';
export const PROGRESS_CLEAR = 'PROGRESS_CLEAR';

export const DIALOG_SHOW = 'DIALOG_SHOW';
export const DIALOG_VISIBLE = 'DIALOG_VISIBLE';
export const DIALOG_RESET = 'DIALOG_RESET';

export const NOTIFICATION_INIT_ROUTE = 'NOTIFICATION_INIT_ROUTE';
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';

export const COMMON_FIREBASE_TOKEN_ID = 'COMMON_FIREBASE_TOKEN_ID';
export const COMMON_LOGOUT = 'COMMON_LOGOUT';
export const COMMON_LOGIN = 'COMMON_LOGIN';
export const COMMON_PASSWORD = 'COMMON_PASSWORD';
export const USER_BRANCH_PATCH = 'USER_BRANCH_PATCH';
export const COMMON_GENDER = 'COMMON_GENDER';
export const COMMON_PRODUCTS = 'COMMON_PRODUCTS';
export const COMMON_PAYMENT_TYPES = 'COMMON_PAYMENT_TYPES';
export const COMMON_ORDER_PAYMENT_TYPES = 'COMMON_ORDER_PAYMENT_TYPES';
export const COMMON_EXPENSE_TYPE = 'COMMON_EXPENSE_TYPE';
export const COMMON_BUSINESS_TYPE = 'COMMON_BUSINESS_TYPE';
export const COMMON_OPERATION_TIME = 'COMMON_OPERATION_TIME';
export const COMMON_APP_GOALS = 'COMMON_APP_GOALS';
export const COMMON_FINANCE_MANAGEMENT = 'COMMON_FINANCE_MANAGEMENT';
export const COMMON_ID_TYPES = 'COMMON_ID_TYPES';

// Bloque 4 multi-sucursal — RN switcher
export const BRANCH_SET_LIST = 'BRANCH_SET_LIST';
export const BRANCH_SET_ACTIVE = 'BRANCH_SET_ACTIVE';
export const BRANCH_MODAL_VISIBLE = 'BRANCH_MODAL_VISIBLE';
export const BRANCH_REFETCH_TICK = 'BRANCH_REFETCH_TICK';

export const NAVIGATION_SHOW_DRAWER = 'NAVIGATION_SHOW_DRAWER';
export const NAVIGATION_DIALOG_VISILE = 'NAVIGATION_DIALOG_VISILE';

export const SPLASHSCREEN_IS_LOADING = 'SPLASHSCREEN_IS_LOADING';
export const SPLASHSCREEN_LANGUAGE = 'SPLASHSCREEN_LANGUAGE';

export const LOGIN_MAIL_CHANGE = 'LOGIN_MAIL_CHANGE';
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE';
export const LOGIN_CLEAR_ERRORS = 'LOGIN_CLEAR_ERRORS';
export const LOGIN_FORM_FAIL = 'LOGIN_FORM_FAIL';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';

export const REGISTER_MAIL_CHANGE = 'REGISTER_MAIL_CHANGE';
export const REGISTER_PASSWORD_CHANGE = 'REGISTER_PASSWORD_CHANGE';
export const REGISTER_CLEAR_ERRORS = 'REGISTER_CLEAR_ERRORS';
export const REGISTER_FORM_FAIL = 'REGISTER_FORM_FAIL';
export const REGISTER_CLEAR = 'REGISTER_CLEAR';
export const REGISTER_NAME_CHANGE = 'REGISTER_NAME_CHANGE';
export const REGISTER_LAST_NAME_CHANGE = 'REGISTER_LAST_NAME_CHANGE';
export const REGISTER_ID_CHANGE = 'REGISTER_ID_CHANGE';
export const REGISTER_PHONE_CHANGE = 'REGISTER_PHONE_CHANGE';
export const REGISTER_COMPANY_CHANGE = 'REGISTER_COMPANY_CHANGE';
export const REGISTER_OPERATION_CHANGE = 'REGISTER_OPERATION_CHANGE';
export const REGISTER_BUSINESS_CHANGE = 'REGISTER_BUSINESS_CHANGE';
export const REGISTER_WEB_CHANGE = 'REGISTER_WEB_CHANGE';
export const REGISTER_FINANCE_CHANGE = 'REGISTER_FINANCE_CHANGE';
export const REGISTER_APP_GOAL_CHANGE = 'REGISTER_APP_GOAL_CHANGE';
export const REGISTER_ROLE_CHANGE = 'REGISTER_ROLE_CHANGE';
export const REGISTER_BUSINESS_TEXT_CHANGE = 'REGISTER_BUSINESS_TEXT_CHANGE';
export const REGISTER_FINANCE_TEXT_CHANGE = 'REGISTER_FINANCE_TEXT_CHANGE';
export const REGISTER_APP_GOAL_TEXT_CHANGE = 'REGISTER_APP_GOAL_TEXT_CHANGE';
export const REGISTER_POSITION_CHANGE = 'REGISTER_POSITION_CHANGE';

export const RECOVER_PASS_GET_MAIL_CHANGE = 'RECOVER_PASS_GET_MAIL_CHANGE';
export const RECOVER_PASS_GET_CLEAR = 'RECOVER_PASS_GET_CLEAR';
export const RECOVER_PASS_GET_FORM_FAIL = 'RECOVER_PASS_GET_FORM_FAIL';

export const RECOVER_PASS_SEND_CODE_CHANGE = 'RECOVER_PASS_SEND_CODE_CHANGE';
export const RECOVER_PASS_SEND_CLEAR = 'RECOVER_PASS_SEND_CLEAR';
export const RECOVER_PASS_SEND_FORM_FAIL = 'RECOVER_PASS_SEND_FORM_FAIL';

export const CHANGE_PASS_PASSWORD_CHANGE = 'CHANGE_PASS_PASSWORD_CHANGE';
export const CHANGE_PASS_CONFIRM_PASSWORD_CHANGE = 'CHANGE_PASS_CONFIRM_PASSWORD_CHANGE';
export const CHANGE_PASS_SEND_CLEAR = 'CHANGE_PASS_SEND_CLEAR';
export const CHANGE_PASS_FORM_FAIL = 'CHANGE_PASS_FORM_FAIL';

export const BUY_QTY_CHANGE = 'BUY_QTY_CHANGE';
export const BUY_CLEAR = 'BUY_CLEAR';
export const BUY_FORM_FAIL = 'BUY_FORM_FAIL';
export const BUY_VALUE_CHANGE = 'BUY_VALUE_CHANGE';
export const BUY_OBS_CHANGE = 'BUY_OBS_CHANGE';
export const BUY_PRODUCT_CHANGE = 'BUY_PRODUCT_CHANGE';
export const BUY_PAYMENT_CHANGE = 'BUY_PAYMENT_CHANGE';
export const BUY_PROVIDER_CHANGE = 'BUY_PROVIDER_CHANGE';
export const BUY_EXPENSE_CHANGE = 'BUY_EXPENSE_CHANGE';

export const CREATE_PROVIDER_NAMES_CHANGE = 'CREATE_PROVIDER_NAMES_CHANGE';
export const CREATE_PROVIDER_LAST_NAMES_CHANGE = 'CREATE_PROVIDER_LAST_NAMES_CHANGE';
export const CREATE_PROVIDER_GENDER_CHANGE = 'CREATE_PROVIDER_GENDER_CHANGE';
export const CREATE_PROVIDER_PHONE_CHANGE = 'CREATE_PROVIDER_PHONE_CHANGE';
export const CREATE_PROVIDER_CITY_CHANGE = 'CREATE_PROVIDER_CITY_CHANGE';
export const CREATE_PROVIDER_CODE_CHANGE = 'CREATE_PROVIDER_CODE_CHANGE';
export const CREATE_PROVIDER_VEREDA_CHANGE = 'CREATE_PROVIDER_VEREDA_CHANGE';
export const CREATE_PROVIDER_SECTOR_CHANGE = 'CREATE_PROVIDER_SECTOR_CHANGE';
export const CREATE_PROVIDER_FARM_CHANGE = 'CREATE_PROVIDER_FARM_CHANGE';
export const CREATE_PROVIDER_TYPE_CHANGE = 'CREATE_PROVIDER_TYPE_CHANGE';
export const CREATE_PROVIDER_CLEAR = 'CREATE_PROVIDER_CLEAR';
export const CREATE_PROVIDER_FORM_FAIL = 'CREATE_PROVIDER_FORM_FAIL';
export const CREATE_PROVIDER_ID_NUMBER_CHANGE = 'CREATE_PROVIDER_ID_NUMBER_CHANGE';

export const PROVIDER_LIST = 'PROVIDER_LIST';
export const PROVIDER_LIST_OFFSET = 'PROVIDER_LIST_OFFSET';
export const PROVIDER_REQUEST_MADE = 'PROVIDER_REQUEST_MADE';
export const PROVIDER_SHOW_LOADER = 'PROVIDER_SHOW_LOADER';
export const PROVIDER_TEXT_CHANGE = 'PROVIDER_TEXT_CHANGE';
export const PROVIDER_SEARCH_BTN = 'PROVIDER_SEARCH_BTN';
export const PROVIDER_CLEAR = 'PROVIDER_CLEAR';

export const BALANCE_LIST = 'BALANCE_LIST';
export const BALANCE_TOTAL = 'BALANCE_TOTAL';
export const BALANCE_REQUEST_MADE = 'BALANCE_REQUEST_MADE';
export const BALANCE_SHOW_LOADER = 'BALANCE_SHOW_LOADER';
export const BALANCE_LIST_OFFSET = 'BALANCE_LIST_OFFSET';
export const BALANCE_SHOW_REFRESH = 'BALANCE_SHOW_REFRESH';
export const BALANCE_REMOVE_ITEM = 'BALANCE_REMOVE_ITEM';
export const BALANCE_MARK_CANCELLED = 'BALANCE_MARK_CANCELLED';

// Bloque cash multi-sucursal: estado del turno activo, scoped a la sucursal
// activa del store. Se refresca via getCashStatus() al cambiar de sucursal,
// al volver a la home, y luego de open/close/loan.
export const CASH_SHIFT_SET = 'CASH_SHIFT_SET';
export const CASH_SHIFT_CLEAR = 'CASH_SHIFT_CLEAR';

export const INVENTORY_LIST = 'INVENTORY_LIST';
export const INVENTORY_TOTAL = 'INVENTORY_TOTAL';
export const INVENTORY_REQUEST_MADE = 'INVENTORY_REQUEST_MADE';
export const INVENTORY_SHOW_LOADER = 'INVENTORY_SHOW_LOADER';
export const INVENTORY_LIST_OFFSET = 'INVENTORY_LIST_OFFSET';
export const INVENTORY_SHOW_REFRESH = 'INVENTORY_SHOW_REFRESH';

export const REMISSION_QTY_CHANGE = 'REMISSION_QTY_CHANGE';
export const REMISSION_CLEAR = 'REMISSION_CLEAR';
export const REMISSION_FORM_FAIL = 'REMISSION_FORM_FAIL';
export const REMISSION_VALUE_CHANGE = 'REMISSION_VALUE_CHANGE';
export const REMISSION_OBS_CHANGE = 'REMISSION_OBS_CHANGE';
export const REMISSION_PRODUCT_CHANGE = 'REMISSION_PRODUCT_CHANGE';
export const REMISSION_HUMIDITY_CHANGE = 'REMISSION_HUMIDITY_CHANGE';
export const REMISSION_WAYBILL_CHANGE = 'REMISSION_WAYBILL_CHANGE';
export const REMISSION_WAREHOUSE_CHANGE = 'REMISSION_WAREHOUSE_CHANGE';
export const REMISSION_TRANSPORTER_CHANGE = 'REMISSION_TRANSPORTER_CHANGE';
export const REMISSION_CUSTOMER_CHANGE = 'REMISSION_CUSTOMER_CHANGE';
export const REMISSION_TOTAL_CHANGE = 'REMISSION_TOTAL_CHANGE';
export const REMISSION_PAYMENT_CHANGE = 'REMISSION_PAYMENT_CHANGE';
export const REMISSION_ORDER_PAYMENT_CHANGE = 'REMISSION_ORDER_PAYMENT_CHANGE';
export const REMISSION_OBSERVATIONS = 'REMISSION_OBSERVATIONS';
export const REMISSION_PAYMENTS_QTY_CHANGE = 'REMISSION_PAYMENTS_QTY_CHANGE';
export const REMISSION_PAYMENT_METHOD_FAIL = 'REMISSION_PAYMENT_METHOD_FAIL';
export const REMISSION_INVOICE_CHANGE = 'REMISSION_INVOICE_CHANGE';

export const HOME_TOTAL = 'HOME_TOTAL';
export const HOME_BUTTON_STATE = 'HOME_BUTTON_STATE';
export const HOME_PERIOD = 'HOME_PERIOD';

export const TERMS_TEXT = 'TERMS_TEXT';

export const ORDERS_LIST = 'ORDERS_LIST';
export const ORDERS_REQUEST_MADE = 'ORDERS_REQUEST_MADE';
export const ORDERS_SHOW_LOADER = 'ORDERS_SHOW_LOADER';
export const ORDERS_SHOW_REFRESH = 'ORDERS_SHOW_REFRESH';
export const ORDERS_LIST_OFFSET = 'ORDERS_LIST_OFFSET';
export const ORDERS_TAB_ACTIVE = 'ORDERS_TAB_ACTIVE';
export const ORDERS_AUTO_VALUE = 'ORDERS_AUTO_VALUE';

export const PAY_ORDER_FORM_FAIL = 'PAY_ORDER_FORM_FAIL';
export const PAY_ORDER_VALUE_CHANGE = 'PAY_ORDER_VALUE_CHANGE';
export const PAY_ORDER_PAYMENT_CHANGE = 'PAY_ORDER_PAYMENT_CHANGE';
export const PAY_ORDER_CLEAR = 'PAY_ORDER_CLEAR';
export const PAY_ORDER_ITEMS = 'PAY_ORDER_ITEMS';
export const PAY_ORDER_QTY_CHANGE = 'PAY_ORDER_QTY_CHANGE';
export const PAY_ORDER_PAYMENT_METHOD_FAIL = 'PAY_ORDER_PAYMENT_METHOD_FAIL';

export const BUY_DETAILS_ITEMS = 'BUY_DETAILS_ITEMS';
export const BUY_DETAILS_PAYMENTS = 'BUY_DETAILS_PAYMENTS';
export const ORDER_DETAILS_ITEMS = 'ORDER_DETAILS_ITEMS';

export const CREATE_PRODUCT_NAME_CHANGE = 'CREATE_PRODUCT_NAME_CHANGE';
export const CREATE_PRODUCT_CODE_CHANGE = 'CREATE_PRODUCT_CODE_CHANGE';
export const CREATE_PRODUCT_PRICE_CHANGE = 'CREATE_PRODUCT_PRICE_CHANGE';
export const CREATE_PRODUCT_FORM_FAIL = 'CREATE_PRODUCT_FORM_FAIL';
export const CREATE_PRODUCT_CLEAR = 'CREATE_PRODUCT_CLEAR';

export const CREATE_CUSTOMER_NAME_CHANGE = 'CREATE_CUSTOMER_NAME_CHANGE';
export const CREATE_CUSTOMER_PHONE_CHANGE = 'CREATE_CUSTOMER_PHONE_CHANGE';
export const CREATE_CUSTOMER_ID_NUMBER_CHANGE = 'CREATE_CUSTOMER_ID_NUMBER_CHANGE';
export const CREATE_CUSTOMER_ADDRESS_CHANGE = 'CREATE_CUSTOMER_ADDRESS_CHANGE';
export const CREATE_CUSTOMER_EMAIL_CHANGE = 'CREATE_CUSTOMER_EMAIL_CHANGE';
export const CREATE_CUSTOMER_FORM_FAIL = 'CREATE_CUSTOMER_FORM_FAIL';
export const CREATE_CUSTOMER_CLEAR = 'CREATE_CUSTOMER_CLEAR';
export const CREATE_CUSTOMER_CITY_CHANGE = 'CREATE_CUSTOMER_CITY_CHANGE';
export const CREATE_CUSTOMER_CITY_NAME_CHANGE = 'CREATE_CUSTOMER_CITY_NAME_CHANGE';
export const CREATE_CUSTOMER_CODE_CHANGE = 'CREATE_CUSTOMER_CODE_CHANGE';
export const CREATE_CUSTOMER_ID_TYPE_CHANGE = 'CREATE_CUSTOMER_ID_TYPE_CHANGE';
export const CREATE_CUSTOMER_DIGIT_CHANGE = 'CREATE_CUSTOMER_DIGIT_CHANGE';
export const CREATE_CUSTOMER_BIRTHDAY_CHANGE = 'CREATE_CUSTOMER_BIRTHDAY_CHANGE';

export const CREATE_PRODUCT_AUNAP_CHANGE = 'CREATE_PRODUCT_AUNAP_CHANGE';
export const CREATE_PRODUCT_ENGLISH_CHANGE = 'CREATE_PRODUCT_ENGLISH_CHANGE';
export const CREATE_PRODUCT_SCIENTIST_CHANGE = 'CREATE_PRODUCT_SCIENTIST_CHANGE';
export const CREATE_PRODUCT_SIZE_CHANGE = 'CREATE_PRODUCT_SIZE_CHANGE';
export const CREATE_PRODUCT_AQUARIUM_CHANGE = 'CREATE_PRODUCT_AQUARIUM_CHANGE';
export const CREATE_PRODUCT_STATUS_CHANGE = 'CREATE_PRODUCT_STATUS_CHANGE';
export const CREATE_PRODUCT_QTY_CHANGE = 'CREATE_PRODUCT_QTY_CHANGE';
export const CREATE_PRODUCT_COLOR_CHANGE = 'CREATE_PRODUCT_COLOR_CHANGE';
export const CREATE_PRODUCT_REF_CHANGE = 'CREATE_PRODUCT_REF_CHANGE';
export const CREATE_PRODUCT_BRAND_CHANGE = 'CREATE_PRODUCT_BRAND_CHANGE';
export const CREATE_PRODUCT_TYPE_CHANGE = 'CREATE_PRODUCT_TYPE_CHANGE';
export const CREATE_PRODUCT_DATE_CHANGE = 'CREATE_PRODUCT_DATE_CHANGE';
export const CREATE_PRODUCT_COST_CHANGE = 'CREATE_PRODUCT_COST_CHANGE';

export const NOTIFICATIONS_LIST = 'NOTIFICATIONS_LIST';
export const NOTIFICATIONS_UNREAD_COUNT = 'NOTIFICATIONS_UNREAD_COUNT';

export const PRODUCTS_LIST = 'PRODUCTS_LIST';
export const PRODUCTS_REQUEST_MADE = 'PRODUCTS_REQUEST_MADE';
export const PRODUCTS_SHOW_LOADER = 'PRODUCTS_SHOW_LOADER';
export const PRODUCTS_SHOW_REFRESH = 'PRODUCTS_SHOW_REFRESH';
export const PRODUCTS_LIST_OFFSET = 'PRODUCTS_LIST_OFFSET';
export const PRODUCTS_CLEAR = 'PRODUCTS_CLEAR';
export const PRODUCTS_SEARCH_BTN = 'PRODUCTS_SEARCH_BTN';
export const PRODUCTS_TEXT_CHANGE = 'PRODUCTS_TEXT_CHANGE';

export const TRANSFER_BRANCH_CHANGE = 'TRANSFER_BRANCH_CHANGE';
export const TRANSFER_PRODUCT_CHANGE = 'TRANSFER_PRODUCT_CHANGE';
export const TRANSFER_QTY_CHANGE = 'TRANSFER_QTY_CHANGE';
export const TRANSFER_CLEAR = 'TRANSFER_CLEAR';
export const TRANSFER_FORM_FAIL = 'TRANSFER_FORM_FAIL';
export const TRANSFER_OBS_CHANGE = 'TRANSFER_OBS_CHANGE';
export const TRANSFER_ORIGIN_INVENTORY = 'TRANSFER_ORIGIN_INVENTORY';
export const TRANSFER_ORIGIN_LOADING = 'TRANSFER_ORIGIN_LOADING';

export const KIT_CLEAR = 'KIT_CLEAR';
export const KIT_FORM_FAIL = 'KIT_FORM_FAIL';
export const KIT_PRODUCT_CHANGE = 'KIT_PRODUCT_CHANGE';
export const KIT_TOTAL_CHANGE = 'KIT_TOTAL_CHANGE';
export const KIT_NAME_CHANGE = 'KIT_NAME_CHANGE';

export const ADD_PRODUCT_KIT_LIST = 'ADD_PRODUCT_KIT_LIST';
export const ADD_PRODUCT_KIT_LIST_OFFSET = 'ADD_PRODUCT_KIT_LIST_OFFSET';
export const ADD_PRODUCT_KIT_REQUEST_MADE = 'ADD_PRODUCT_KIT_REQUEST_MADE';
export const ADD_PRODUCT_KIT_SHOW_LOADER = 'ADD_PRODUCT_KIT_SHOW_LOADER';
export const ADD_PRODUCT_KIT_TEXT_CHANGE = 'ADD_PRODUCT_KIT_TEXT_CHANGE';
export const ADD_PRODUCT_KIT_SEARCH_BTN = 'ADD_PRODUCT_KIT_SEARCH_BTN';
export const ADD_PRODUCT_KIT_CLEAR = 'ADD_PRODUCT_KIT_CLEAR';

export const INVENTORY_LIST_SHOW_REFRESH = 'INVENTORY_LIST_SHOW_REFRESH';
export const INVENTORY_LIST_LIST = 'INVENTORY_LIST_LIST';
export const INVENTORY_LIST_REQUEST_MADE = 'INVENTORY_LIST_REQUEST_MADE';
export const INVENTORY_LIST_SHOW_LOADER = 'INVENTORY_LIST_SHOW_LOADER';
export const INVENTORY_LIST_LIST_OFFSET = 'INVENTORY_LIST_LIST_OFFSET';
export const INVENTORY_LIST_TEXT = 'INVENTORY_LIST_TEXT';
export const INVENTORY_LIST_SEARCH = 'INVENTORY_LIST_SEARCH';

export const QR_SCAN_CLEAR = 'QR_SCAN_CLEAR';
export const QR_SCAN_CAMERA_ACTIVE = 'QR_SCAN_CAMERA_ACTIVE';
export const QR_SCAN_CODE_SCANNED = 'QR_SCAN_CODE_SCANNED';
export const QR_SCAN_HAS_PERMISSION = 'QR_SCAN_HAS_PERMISSION';

export const BOX_MONEY_CHANGE = 'BOX_MONEY_CHANGE';
export const BOX_CLEAR = 'BOX_CLEAR';
export const BOX_FORM_FAIL = 'BOX_FORM_FAIL';
export const BOX_SELECT_CHANGE = 'BOX_SELECT_CHANGE';
export const BOX_BALANCE = 'BOX_BALANCE';
export const BOX_BALANCE_SHOW = 'BOX_BALANCE_SHOW';
export const BOX_BALANCE_TYPE_SELECTED = 'BOX_BALANCE_TYPE_SELECTED';
export const BOX_HISTORY = 'BOX_HISTORY';

export const CREATE_PRODUCT_CATEGORY_NAME_CHANGE = 'CREATE_PRODUCT_CATEGORY_NAME_CHANGE';
export const CREATE_PRODUCT_CATEGORY_FORM_FAIL = 'CREATE_PRODUCT_CATEGORY_FORM_FAIL';
export const CREATE_PRODUCT_CATEGORY_CLEAR = 'CREATE_PRODUCT_CATEGORY_CLEAR';

export const PRODUCT_CATEGORIES_LIST = 'PRODUCT_CATEGORIES_LIST';
export const PRODUCT_CATEGORIES_LIST_OFFSET = 'PRODUCT_CATEGORIES_LIST_OFFSET';
export const PRODUCT_CATEGORIES_REQUEST_MADE = 'PRODUCT_CATEGORIES_REQUEST_MADE';
export const PRODUCT_CATEGORIES_SHOW_LOADER = 'PRODUCT_CATEGORIES_SHOW_LOADER';
export const PRODUCT_CATEGORIES_TEXT_CHANGE = 'PRODUCT_CATEGORIES_TEXT_CHANGE';
export const PRODUCT_CATEGORIES_SEARCH_BTN = 'PRODUCT_CATEGORIES_SEARCH_BTN';
export const PRODUCT_CATEGORIES_CLEAR = 'PRODUCT_CATEGORIES_CLEAR';

export const PRODUCT_VARIATIONS_LIST = 'PRODUCT_VARIATIONS_LIST';
export const PRODUCT_VARIATIONS_LIST_OFFSET = 'PRODUCT_VARIATIONS_LIST_OFFSET';
export const PRODUCT_VARIATIONS_REQUEST_MADE = 'PRODUCT_VARIATIONS_REQUEST_MADE';
export const PRODUCT_VARIATIONS_SHOW_LOADER = 'PRODUCT_VARIATIONS_SHOW_LOADER';
export const PRODUCT_VARIATIONS_TEXT_CHANGE = 'PRODUCT_VARIATIONS_TEXT_CHANGE';
export const PRODUCT_VARIATIONS_SEARCH_BTN = 'PRODUCT_VARIATIONS_SEARCH_BTN';
export const PRODUCT_VARIATIONS_CLEAR = 'PRODUCT_VARIATIONS_CLEAR';

export const INVENTORY_CATEGORY_SHOW_REFRESH = 'INVENTORY_CATEGORY_SHOW_REFRESH';
export const INVENTORY_CATEGORY_LIST = 'INVENTORY_CATEGORY_LIST';
export const INVENTORY_CATEGORY_REQUEST_MADE = 'INVENTORY_CATEGORY_REQUEST_MADE';
export const INVENTORY_CATEGORY_SHOW_LOADER = 'INVENTORY_CATEGORY_SHOW_LOADER';
export const INVENTORY_CATEGORY_LIST_OFFSET = 'INVENTORY_CATEGORY_LIST_OFFSET';
export const INVENTORY_CATEGORY_TEXT = 'INVENTORY_CATEGORY_TEXT';
export const INVENTORY_CATEGORY_SEARCH = 'INVENTORY_CATEGORY_SEARCH';

export const NEW_SALE_LIST = 'NEW_SALE_LIST';
export const NEW_SALE_LIST_OFFSET = 'NEW_SALE_LIST_OFFSET';
export const NEW_SALE_REQUEST_MADE = 'NEW_SALE_REQUEST_MADE';
export const NEW_SALE_SHOW_LOADER = 'NEW_SALE_SHOW_LOADER';
export const NEW_SALE_TEXT_CHANGE = 'NEW_SALE_TEXT_CHANGE';
export const NEW_SALE_SEARCH_BTN = 'NEW_SALE_SEARCH_BTN';
export const NEW_SALE_CLEAR = 'NEW_SALE_CLEAR';
export const NEW_SALE_FORM_FAIL = 'NEW_SALE_FORM_FAIL';
export const NEW_SALE_PRODUCT_CHANGE = 'NEW_SALE_PRODUCT_CHANGE';
export const NEW_SALE_TOTAL_CHANGE = 'NEW_SALE_TOTAL_CHANGE';
export const NEW_SALE_CUSTOMER_CHANGE = 'NEW_SALE_CUSTOMER_CHANGE';
export const NEW_SALE_CUSTOMER_VISIBLE = 'NEW_SALE_CUSTOMER_VISIBLE';
export const NEW_SALE_PRODUCT_SELECTED = 'NEW_SALE_PRODUCT_SELECTED';

export const CONFIRM_CASH_ORDER_CONFIRM_VALUE_CHANGE = 'CONFIRM_CASH_ORDER_CONFIRM_VALUE_CHANGE';
export const CONFIRM_CASH_ORDER_CLEAR = 'CONFIRM_CASH_ORDER_CLEAR';
export const CONFIRM_CASH_ORDER_FORM_FAIL = 'CONFIRM_CASH_ORDER_FORM_FAIL';
export const CONFIRM_CASH_ORDER_RETURN = 'CONFIRM_CASH_ORDER_RETURN';
export const CONFIRM_CASH_INVOICE = 'CONFIRM_CASH_INVOICE';

export const CREATE_CARD_FORM = 'CREATE_CARD_FORM';
export const CREATE_CARD_CCV_ERROR = 'CREATE_CARD_CCV_ERROR';
export const CREATE_CARD_EXPIRY_ERROR = 'CREATE_CARD_EXPIRY_ERROR';
export const CREATE_CARD_NAME_ERROR = 'CREATE_CARD_NAME_ERROR';
export const CREATE_CARD_NUMBER_ERROR = 'CREATE_CARD_NUMBER_ERROR';
export const CREATE_CARD_CLEAR = 'CREATE_CARD_CLEAR';
export const CREATE_CARD_IDENTIFICATION = 'CREATE_CARD_IDENTIFICATION';
export const CREATE_CARD_IDENTIFICATION_ERROR = 'CREATE_CARD_IDENTIFICATION_ERROR';
export const CREATE_CARD_MODE = 'CREATE_CARD_MODE';

export const PLAN_INFO = 'PLAN_INFO';
export const PLAN_PRICE = 'PLAN_PRICE';
export const PLAN_CLEAR = 'PLAN_CLEAR';
export const PLAN_ERROR = 'PLAN_ERROR';
export const PLAN_PLAN = 'PLAN_PLAN';
export const PLAN_PLAN_SELECTED = 'PLAN_PLAN_SELECTED';

export const ADD_INVENTORY_LIST = 'ADD_INVENTORY_LIST';
export const ADD_INVENTORY_LIST_OFFSET = 'ADD_INVENTORY_LIST_OFFSET';
export const ADD_INVENTORY_REQUEST_MADE = 'ADD_INVENTORY_REQUEST_MADE';
export const ADD_INVENTORY_SHOW_LOADER = 'ADD_INVENTORY_SHOW_LOADER';
export const ADD_INVENTORY_TEXT_CHANGE = 'ADD_INVENTORY_TEXT_CHANGE';
export const ADD_INVENTORY_SEARCH_BTN = 'ADD_INVENTORY_SEARCH_BTN';
export const ADD_INVENTORY_CLEAR = 'ADD_INVENTORY_CLEAR';
export const ADD_INVENTORY_PRODUCT_CHANGE = 'ADD_INVENTORY_PRODUCT_CHANGE';
export const ADD_INVENTORY_CUSTOMER_CHANGE = 'ADD_INVENTORY_CUSTOMER_CHANGE';
export const ADD_INVENTORY_CUSTOMER_VISIBLE = 'ADD_INVENTORY_CUSTOMER_VISIBLE';
export const ADD_INVENTORY_PRODUCT_SELECTED = 'ADD_INVENTORY_PRODUCT_SELECTED';

export const PRINTER_SETTINGS_LOAD = 'PRINTER_SETTINGS_LOAD';
export const PRINTER_SETTINGS_PAIRED = 'PRINTER_SETTINGS_PAIRED';
export const PRINTER_SETTINGS_SELECTED = 'PRINTER_SETTINGS_SELECTED';
export const PRINTER_SETTINGS_AUTO_PRINT = 'PRINTER_SETTINGS_AUTO_PRINT';
export const PRINTER_SETTINGS_OPEN_DRAWER = 'PRINTER_SETTINGS_OPEN_DRAWER';
export const PRINTER_SETTINGS_LOADING = 'PRINTER_SETTINGS_LOADING';
export const PRINTER_SETTINGS_CLEAR = 'PRINTER_SETTINGS_CLEAR';
export const PRINTER_SETTINGS_FOUND = 'PRINTER_SETTINGS_FOUND';
export const PRINTER_SETTINGS_SCANNING = 'PRINTER_SETTINGS_SCANNING';
export const PRINTER_SETTINGS_PAIRING = 'PRINTER_SETTINGS_PAIRING';

export const BILLING_LOAD = 'BILLING_LOAD';
export const BILLING_LOADING = 'BILLING_LOADING';
export const BILLING_ERROR = 'BILLING_ERROR';
export const BILLING_CLEAR = 'BILLING_CLEAR';
export const BILLING_BUSY = 'BILLING_BUSY';